# Generated by Django 5.0.8 on 2025-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('author', 'Author'), ('modarator', 'Modarator')], default='modarator', max_length=10),
        ),
    ]
