# Generated by Django 5.0.8 on 2025-01-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_categories_blog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bad_reactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='good_reactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
