# Generated by Django 5.0.8 on 2025-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogreactions_delete_blogreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreactions',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='blogreactions',
            name='reaction',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
